#!/usr/bin/env node
/**
 * Dev-only: rasterizes assets/deepseek-128px.png into Unicode half-block art
 * via the `chafa` CLI and writes src/tui/logoArt.generated.ts. Not part of
 * `pnpm run build` — chafa is never a runtime dependency of dsh-tui, only a
 * local tool (e.g. `brew install chafa`) used to regenerate this file after
 * the source image changes.
 *
 * Usage: node scripts/generate-logo.mjs
 */

import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const pngPath = `${root}assets/deepseek-128px.png`
const outPath = `${root}src/tui/logoArt.generated.ts`

const raw = execFileSync(
  'chafa',
  ['--format', 'symbols', '--symbols=half', '--color-space=rgb', '--size=16x16', pngPath],
  { encoding: 'utf8' },
)

// Strip chafa's own cursor-visibility toggles (DEC private mode ?25l/?25h) —
// irrelevant once this is embedded as static text inside another program's
// own render loop.
const lines = raw
  .replace(/\x1b\[\?25[lh]/g, '')
  .split('\n')
  .filter((_, i, all) => !(i === all.length - 1 && all[i] === ''))

const body = lines.map(line => JSON.stringify(line)).join(',\n  ')

const out = `/**
 * Generated by \`node scripts/generate-logo.mjs\` from
 * \`assets/deepseek-128px.png\` via chafa (half-block, 16x16, rgb color
 * space). Do not hand-edit — re-run the script after the source image
 * changes; requires \`chafa\` installed locally (e.g. \`brew install chafa\`).
 * @module @tomowang/dsh-tui/tui/logoArt.generated
 */

/** One entry per output row; each line carries embedded 24-bit ANSI SGR color codes. */
export const LOGO_HALF_BLOCK: readonly string[] = [
  ${body},
]
`

writeFileSync(outPath, out)
console.log(`wrote ${lines.length} lines to ${outPath}`)
